window.MELEC={
  activities:[
    {id:'A1',label:'Préparation des opérations de réalisation, de mise en service, de maintenance'},
    {id:'A2',label:'Réalisation'},{id:'A3',label:'Mise en service'},{id:'A4',label:'Maintenance'},{id:'A5',label:'Communication'}
  ],
  tasks:[
    ['T1-1','A1','Prendre connaissance du dossier relatif aux opérations à réaliser, le constituer pour une opération simple'],['T1-2','A1','Rechercher et expliquer les informations relatives aux opérations et aux conditions d’exécution'],['T1-3','A1','Vérifier et compléter si besoin la liste des matériels électriques, équipements et outillages nécessaires aux opérations'],['T1-4','A1','Répartir les tâches en fonction des habilitations, des certifications des équipiers et du planning des autres intervenants'],
    ['T2-1','A2','Organiser le poste de travail'],['T2-2','A2','Implanter, poser, installer les matériels électriques'],['T2-3','A2','Câbler, raccorder les matériels électriques'],['T2-4','A2','Gérer les activités de son équipe'],['T2-5','A2','Coordonner son activité par rapport à celles des autres intervenants'],['T2-6','A2','Mener son activité de manière éco-responsable'],
    ['T3-1','A3','Réaliser les vérifications, les réglages, les paramétrages et les essais nécessaires à la mise en service'],['T3-2','A3','Participer à la réception technique et aux levées de réserves de l’installation'],['T4-1','A4','Réaliser une opération de maintenance préventive'],['T4-2','A4','Réaliser une opération de dépannage'],['T5-1','A5','Participer à la mise à jour du dossier technique de l’installation'],['T5-2','A5','Échanger sur le déroulement des opérations, expliquer le fonctionnement de l’installation'],['T5-3','A5','Conseiller le client, lui proposer une prestation complémentaire, une modification ou une amélioration']
  ].map(([id,activity,label])=>({id,activity,label})),
  competencies:[
    ['C1','Analyser les conditions de l’opération et son contexte',['Les informations nécessaires sont recueillies','Les contraintes techniques et d’exécution sont repérées','Les contraintes liées à l’efficacité énergétique sont repérées','Les risques professionnels sont évalués','Les mesures de prévention de santé et sécurité au travail sont proposées','Les contraintes environnementales sont recensées','Les interactions avec les autres intervenants sont repérées','Les habilitations et certifications nécessaires sont identifiées']],
    ['C2','Organiser l’opération dans son contexte',['Les matériels, équipements et outillages manquants sont listés','Le bon d’approvisionnement ou de commande est complété','Les tâches sont réparties selon les habilitations et certifications','La répartition prend en compte les autres intervenants','Les activités sont organisées chronologiquement','Les contraintes du poste sont prises en compte','Les activités sont réorganisées selon les aléas','Les règles de santé et sécurité sont respectées','Le poste est organisé avec ergonomie','Le poste est approvisionné','Le lieu est restitué propre et en ordre']],
    ['C3','Définir une installation à l’aide de solutions préétablies',['Le dossier technique des opérations est constitué et complet','La solution technique répond au besoin du client et est pertinente','La solution intègre les enjeux d’efficacité énergétique']],
    ['C4','Réaliser une installation de manière éco-responsable',['Les matériels sont posés conformément aux prescriptions et règles de l’art','Le façonnage est conforme','Les câblages et raccordements sont conformes','Les adaptations techniques nécessaires sont réalisées','La réalisation respecte l’efficacité énergétique','Les autocontrôles sont réalisés et renseignés','Les déchets sont triés et évacués sélectivement','Le consommable est utilisé sans gaspillage','Les règles de santé et sécurité sont respectées','Les lieux et les biens sont respectés']],
    ['C5','Contrôler les grandeurs caractéristiques de l’installation',['Les contrôles sont réalisés','Les mesures sont réalisées','Les mesures liées à l’efficacité énergétique sont réalisées','Les essais adaptés sont réalisés','Les grandeurs sont correctement interprétées','Les règles de santé et sécurité sont respectées']],
    ['C6','Régler, paramétrer les matériels de l’installation',['Les réglages sont conformes aux prescriptions','Les réglages prennent en compte l’efficacité énergétique','Les paramétrages guidés sont conformes','Les règles de santé et sécurité sont respectées']],
    ['C7','Valider le fonctionnement de l’installation',['L’installation est mise en fonctionnement conformément aux prescriptions','Le fonctionnement est conforme au cahier des charges','Les opérations nécessaires à la levée de réserves sont faites','Les règles de santé et sécurité sont respectées']],
    ['C8','Diagnostiquer un dysfonctionnement',['Les informations relatives au dysfonctionnement sont analysées','Le fonctionnement de l’installation est analysé','Le diagnostic est posé','Le diagnostic est pertinent et complet','Les règles de santé et sécurité sont respectées']],
    ['C9','Remplacer un matériel électrique',['Le matériel à remplacer est identifié','Le matériel est correctement déposé','Le matériel de remplacement est correctement choisi','Le matériel de remplacement est correctement installé','Le fonctionnement est vérifié après rétablissement des énergies','Les règles de santé et sécurité sont respectées']],
    ['C10','Exploiter les outils numériques dans le contexte professionnel',['Les applications numériques sont exploitées avec pertinence','La recherche d’information est pertinente','Les moyens numériques de communication sont exploités avec pertinence','Les outils de communication sont exploités de manière éthique et responsable']],
    ['C11','Compléter les documents liés aux opérations',['Les documents à compléter sont identifiés','Les informations nécessaires sont identifiées','Les documents sont complétés ou modifiés correctement']],
    ['C12','Communiquer entre professionnels sur l’opération',['Les informations nécessaires à la communication sont identifiées','Les contraintes techniques sont expliquées','Les choix technologiques sont argumentés','Les choix économiques sont expliqués','Les contraintes de performance énergétique sont expliquées','L’état d’avancement est justifié','Les difficultés sont remontées à la hiérarchie']],
    ['C13','Communiquer avec le client/usager sur l’opération',['Les besoins du client sont collectés','Les contraintes d’utilisation et de performance énergétique sont expliquées','Les usages et le fonctionnement sont maîtrisés par le client','Les choix technologiques et économiques sont expliqués','L’avancement et ses contraintes sont expliqués','Les prestations complémentaires sont expliquées','La satisfaction client est collectée']]
  ].map(([id,label,criteria])=>({id,label,criteria})),
  links:{
    'T1-1':{C1:2,C3:2,C10:2,C11:2,C12:2},'T1-2':{C1:2,C10:2,C12:2},'T1-3':{C2:2,C10:1,C11:2,C12:1},'T1-4':{C1:2,C2:2,C10:1,C12:1},
    'T2-1':{C2:2,C10:1},'T2-2':{C2:1,C4:2,C5:2,C10:1,C11:1},'T2-3':{C2:1,C4:2,C5:2,C10:1,C11:1},'T2-4':{C2:2,C10:1,C12:2},'T2-5':{C2:2,C10:1,C12:2},'T2-6':{C2:2,C4:2,C10:1},
    'T3-1':{C2:1,C5:2,C6:2,C7:2,C8:1,C9:1,C10:1},'T3-2':{C2:1,C5:2,C6:2,C7:2,C8:1,C9:1,C10:1},'T4-1':{C2:1,C5:2,C7:2,C9:2,C10:1},'T4-2':{C2:2,C5:2,C6:2,C7:2,C8:2,C9:2,C10:1},
    'T5-1':{C10:2,C11:2,C12:2,C13:1},'T5-2':{C10:1,C12:2,C13:2},'T5-3':{C1:1,C10:1,C11:1,C12:1,C13:2}
  }
};

// Compléments structurés issus de l'arrêté du 1er mars 2024 (JORF du 8 mars 2024).
MELEC.source={title:'Arrêté du 1er mars 2024 — Bac Pro MELEC',publication:'JORF n°57 du 8 mars 2024',file:'BO Referentiel melec.pdf'};
MELEC.sectors=['Bâtiment résidentiel','Bâtiment tertiaire','Bâtiment industriel','Industrie','Réseaux et infrastructures','Systèmes énergétiques autonomes et embarqués'];
MELEC.knowledge={energy:'Chaîne d’énergie',information:'Chaîne d’information',measures:'Grandeurs électriques, mécaniques et dimensionnelles',tools:'Ressources et outils professionnels',qsse:'Qualité - Santé - Sécurité - Environnement',diagnostic:'Diagnostic',communication:'Communication'};
MELEC.attitudes={AP1:'Faire preuve de rigueur et de précision',AP2:'Faire preuve d’esprit d’équipe',AP3:'Faire preuve de curiosité et d’écoute',AP4:'Faire preuve d’initiative',AP5:'Faire preuve d’analyse critique'};
MELEC.blocks=[
  {id:'B1',unit:'U2',label:'Préparation des opérations à réaliser',competencies:['C1','C3','C10','C11']},
  {id:'B2',unit:'U31',label:'Réalisation et mise en service d’une installation',competencies:['C2','C4','C5','C6','C7','C12','C13']},
  {id:'B3',unit:'U32',label:'Maintenance d’une installation',competencies:['C8','C9']}
];
const taskAutonomy={
  'T1-1':'Totale','T1-2':'Partielle','T1-3':'Totale','T1-4':'Partielle','T2-1':'Totale','T2-2':'Totale','T2-3':'Totale','T2-4':'Partielle','T2-5':'Totale','T2-6':'Totale','T3-1':'Totale','T3-2':'Partielle','T4-1':'Totale','T4-2':'Totale','T5-1':'Partielle','T5-2':'Partielle','T5-3':'Partielle'
};
MELEC.tasks.forEach(t=>t.autonomy=taskAutonomy[t.id]);
const competencyDetails={
  C1:{knowledge:['energy','information','tools','qsse','communication'],attitudes:['AP1','AP5']},C2:{knowledge:['energy','information','tools','qsse','communication'],attitudes:['AP1','AP2','AP4']},C3:{knowledge:['energy','information','measures','tools','qsse','communication'],attitudes:['AP1','AP3','AP5']},C4:{knowledge:['energy','information','measures','tools','qsse'],attitudes:['AP1','AP2','AP4']},C5:{knowledge:['energy','information','measures','tools','qsse'],attitudes:['AP1','AP5']},C6:{knowledge:['energy','information','measures','tools','qsse'],attitudes:['AP1']},C7:{knowledge:['energy','information','measures','tools','qsse'],attitudes:['AP1']},C8:{knowledge:['energy','information','measures','tools','qsse','diagnostic'],attitudes:['AP1','AP4','AP5']},C9:{knowledge:['energy','information','measures','tools','qsse'],attitudes:['AP1','AP4']},C10:{knowledge:['energy','information','tools','qsse','communication'],attitudes:['AP1','AP4','AP5']},C11:{knowledge:['energy','information','tools','qsse','communication'],attitudes:['AP1']},C12:{knowledge:['energy','information','measures','tools','qsse','communication'],attitudes:['AP2','AP3','AP5']},C13:{knowledge:['energy','information','qsse','communication'],attitudes:['AP3','AP4','AP5']}
};
MELEC.competencies.forEach(c=>Object.assign(c,competencyDetails[c.id],{block:MELEC.blocks.find(b=>b.competencies.includes(c.id)).id,unit:MELEC.blocks.find(b=>b.competencies.includes(c.id)).unit}));
